services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.standalone
    container_name: api
    # restart: unless-stopped
    env_file:
      - ./apps/api/.env
    ports:
      - "5001:5001"
    networks:
      - main_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: unless-stopped
    ports:
      - "88:80"
    networks:
      - main_network
    volumes:
      - ./nginx/default.api.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      api:
        condition: service_started

networks:
  main_network:
    driver: bridge
