services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.standalone
    container_name: sundate-api
    # restart: unless-stopped
    env_file:
      - ./apps/api/.env
    networks:
      - sundate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: sundate-nginx
    # restart: unless-stopped
    ports:
      - '88:80'
    volumes:
      - ./nginx/default.api.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      api:
        condition: service_started
    networks:
      - sundate-network

networks:
  sundate-network:
    driver: bridge
