version: '3'
services:
  api:
    restart: unless-stopped
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    networks:
      - sundate_network

  docs:
    restart: unless-stopped
    container_name: docs
    build:
      context: .
      dockerfile: apps/docs/Dockerfile
    env_file:
      - ./apps/docs/.env
    networks:
      - sundate_network

  dashboard:
    restart: unless-stopped
    container_name: dashboard
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    env_file:
      - ./apps/dashboard/.env
    networks:
      - sundate_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      docs:
        condition: service_started
      api:
        condition: service_started
    networks:
      - sundate_network

networks:
  sundate_network:
    # driver: bridge
    # define as external to use the same network as the other services
    external: true
