version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sundate-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sundate-cafe
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb-dev:/data/db
    networks:
      - sundate-network-dev
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: sundate-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5001
      MONGO_URI: mongodb://admin:password123@mongodb:27017/sundate-cafe?authSource=admin
    ports:
      - "5001:5001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sundate-network-dev
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: sundate-web-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:5001
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - sundate-network-dev
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Documentation Site
  docs:
    build:
      context: ./apps/docs
      dockerfile: Dockerfile
    container_name: sundate-docs-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - sundate-network-dev
    volumes:
      - ./apps/docs:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sundate-network-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
