FROM node:22-alpine
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy source code (excluding node_modules due to .dockerignore)
COPY . .

EXPOSE 5001

CMD ["npm", "start"]
